generate:
  packagePrefix: "com.hym.devtool."
  diskPath: "src/main/java/com/hym/devtool/"
  controllerPath: "module/"
  model-path: "src/main/java/com/hym/devtool/"
  mapper-path: "src/main/resources/"
  dao-path: "src/main/java/com/hym/devtool/"
  service-path: "src/main/java/com/hym/devtool/"
  test-path: "src/test/java/com/hym/devtool/api/"
  pageListPath: "com.hym.devtool.base.pagelist.PageList"
  apiResultPath: "com.hym.devtool.base.ApiResult"
  testUtilPath: "cn.com.ecomonitor.eco.TestUtil"
  sql-builder-path: ""
  dao-name: "Mapper"
  spring-properties-active: "dev"
  main-class: "DevtoolApplication"
  application-path: "com.hym.devtool"

db:
  driver: "com.mysql.cj.jdbc.Driver"
  url: "jdbc:mysql://47.107.67.156:3306/iemproject_data_01?useTimezone=true&serverTimezone=GMT%2B8"
  username: "root"
  password: "HuihangMysqlTest@2021!"